export const invoicesData = [
    {
        restaurantName: "Dragon Wok",
        logo: "/table-pic.png",
        billingCycle: "February 2025",
        package: "$4250.00",
        deductions: "-$150.00",
        netPayable: "$4100.00",
        status: "Generated",
    },
    {
        restaurantName: "Dragon Wok",
        logo: "/table-pic.png",
        billingCycle: "February 2025",
        package: "$4250.00",
        deductions: "-$150.00",
        netPayable: "$4100.00",
        status: "Paid",
    },
    {
        restaurantName: "Dragon Wok",
        logo: "/table-pic.png",
        billingCycle: "February 2025",
        package: "$4250.00",
        deductions: "-$150.00",
        netPayable: "$4100.00",
        status: "Overdue",
    },
    {
        restaurantName: "Dragon Wok",
        logo: "/table-pic.png",
        billingCycle: "February 2025",
        package: "$4250.00",
        deductions: "-$150.00",
        netPayable: "$4100.00",
        status: "Generated",
    },
    {
        restaurantName: "Dragon Wok",
        logo: "/table-pic.png",
        billingCycle: "February 2025",
        package: "$4250.00",
        deductions: "-$150.00",
        netPayable: "$4100.00",
        status: "Paid",
    },
];
