// constants/promotions.ts

export const promotionsData = [
  {
    sl: 1,
    title: "First Coupon",
    code: "51KOH55",
    buyItem: "Burger",
    getItem: "Burger",
    branch: "All Branches",
    totalUsage: "10 Orders",
    status: true,
  },
  {
    sl: 2,
    title: "First Coupon",
    code: "51KOH55",
    buyItem: "Burger",
    getItem: "Burger",
    branch: "All Branches",
    totalUsage: "10 Orders",
    status: true,
  },
  {
    sl: 3,
    title: "First Coupon",
    code: "51KOH55",
    buyItem: "Burger",
    getItem: "Burger",
    branch: "All Branches",
    totalUsage: "10 Orders",
    status: true,
  },
  {
    sl: 4,
    title: "First Coupon",
    code: "51KOH55",
    buyItem: "Burger",
    getItem: "Burger",
    branch: "All Branches",
    totalUsage: "10 Orders",
    status: true,
  },
  {
    sl: 5,
    title: "First Coupon",
    code: "51KOH55",
    buyItem: "Burger",
    getItem: "Burger",
    branch: "All Branches",
    totalUsage: "10 Orders",
    status: true,
  },
];
